'''
(huri) C:\Users\21344>conda list
# packages in environment at D:\Anaconda3\envs\huri:
#
# Name                    Version                   Build  Channel
absl-py                   2.1.0                    pypi_0    pypi
aiohappyeyeballs          2.4.3                    pypi_0    pypi
aiohttp                   3.10.10                  pypi_0    pypi
aiohttp-cors              0.7.0                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
anyio                     4.6.2.post1              pypi_0    pypi
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
blinker                   1.8.2                    pypi_0    pypi
ca-certificates           2024.8.30            h56e8100_0    conda-forge
cachetools                5.5.0                    pypi_0    pypi
certifi                   2024.8.30                pypi_0    pypi
cffi                      1.17.1                   pypi_0    pypi
charset-normalizer        3.4.0                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.1.0                    pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
colorful                  0.5.6                    pypi_0    pypi
colorlog                  6.9.0                    pypi_0    pypi
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
configargparse            1.7                      pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
cryptography              43.0.3                   pypi_0    pypi
cupy-cuda12x              13.3.0                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
dash                      2.18.2                   pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
debugpy                   1.6.7            py39hd77b12b_0    defaults
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
deprecated                1.2.14                   pypi_0    pypi
distlib                   0.3.9                    pypi_0    pypi
dm-tree                   0.1.8                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
executing                 2.1.0              pyhd8ed1ab_0    conda-forge
farama-notifications      0.0.4                    pypi_0    pypi
fastapi                   0.115.4                  pypi_0    pypi
fastjsonschema            2.20.0                   pypi_0    pypi
fastrlock                 0.8.2                    pypi_0    pypi
filelock                  3.16.1                   pypi_0    pypi
flask                     3.0.3                    pypi_0    pypi
fonttools                 4.54.1                   pypi_0    pypi
frozenlist                1.5.0                    pypi_0    pypi
fsspec                    2024.10.0                pypi_0    pypi
google-api-core           2.22.0                   pypi_0    pypi
google-auth               2.35.0                   pypi_0    pypi
googleapis-common-protos  1.65.0                   pypi_0    pypi
grpcio                    1.51.1                   pypi_0    pypi
gym                       0.26.2                   pypi_0    pypi
gym-notices               0.0.8                    pypi_0    pypi
gymnasium                 0.28.1                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httptools                 0.6.4                    pypi_0    pypi
idna                      3.10                     pypi_0    pypi
imageio                   2.36.0                   pypi_0    pypi
importlib-metadata        8.4.0                    pypi_0    pypi
importlib-resources       6.4.5                    pypi_0    pypi
ipykernel                 6.29.5             pyh4bbf305_0    conda-forge
ipython                   8.18.1                   pypi_0    pypi
ipywidgets                8.1.5                    pypi_0    pypi
itsdangerous              2.2.0                    pypi_0    pypi
jax-jumpy                 1.0.0                    pypi_0    pypi
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2024.10.1                pypi_0    pypi
jupyter_client            8.6.3              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2            py39hcbf5309_0    conda-forge
jupyterlab-widgets        3.0.13                   pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
libsodium                 1.0.18               h8d14728_1    conda-forge
llvmlite                  0.43.0                   pypi_0    pypi
lz4                       4.3.3                    pypi_0    pypi
markdown                  3.7                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                3.0.2                    pypi_0    pypi
matplotlib                3.8.4                    pypi_0    pypi
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msgpack                   1.1.0                    pypi_0    pypi
multidict                 6.1.0                    pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
networkx                  3.2.1                    pypi_0    pypi
numba                     0.60.0                   pypi_0    pypi
numpy                     1.22.4                   pypi_0    pypi
open3d                    0.18.0                   pypi_0    pypi
opencensus                0.11.4                   pypi_0    pypi
opencensus-context        0.1.3                    pypi_0    pypi
opencv-contrib-python     4.6.0.66                 pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
openssl                   3.0.15               h827c3e9_0    defaults
opentelemetry-api         1.27.0                   pypi_0    pypi
opentelemetry-exporter-otlp 1.27.0                   pypi_0    pypi
opentelemetry-exporter-otlp-proto-common 1.27.0                   pypi_0    pypi
opentelemetry-exporter-otlp-proto-grpc 1.27.0                   pypi_0    pypi
opentelemetry-exporter-otlp-proto-http 1.27.0                   pypi_0    pypi
opentelemetry-proto       1.27.0                   pypi_0    pypi
opentelemetry-sdk         1.27.0                   pypi_0    pypi
opentelemetry-semantic-conventions 0.48b0                   pypi_0    pypi
packaging                 24.1               pyhd8ed1ab_0    conda-forge
panda3d                   1.10.14                  pypi_0    pypi
pandas                    2.2.3                    pypi_0    pypi
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    11.0.0                   pypi_0    pypi
pip                       24.2             py39haa95532_0    defaults
platformdirs              4.3.6              pyhd8ed1ab_0    conda-forge
plotly                    5.24.1                   pypi_0    pypi
pmw                       2.1.1                    pypi_0    pypi
prometheus-client         0.21.0                   pypi_0    pypi
prompt-toolkit            3.0.48             pyha770c72_0    conda-forge
prompt_toolkit            3.0.48               hd8ed1ab_0    conda-forge
propcache                 0.2.0                    pypi_0    pypi
proto-plus                1.25.0                   pypi_0    pypi
protobuf                  3.20.3                   pypi_0    pypi
psutil                    6.1.0                    pypi_0    pypi
pure_eval                 0.2.3              pyhd8ed1ab_0    conda-forge
py-cpuinfo                9.0.0                    pypi_0    pypi
py-spy                    0.4.0                    pypi_0    pypi
pyarrow                   18.0.0                   pypi_0    pypi
pyasn1                    0.6.1                    pypi_0    pypi
pyasn1-modules            0.4.1                    pypi_0    pypi
pybind11                  2.13.6           py39h214f63a_0    defaults
pybind11-global           2.13.6           py39h214f63a_0    defaults
pycparser                 2.22                     pypi_0    pypi
pydantic                  2.9.2                    pypi_0    pypi
pydantic-core             2.23.4                   pypi_0    pypi
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 24.2.1                   pypi_0    pypi
pyparsing                 3.2.0                    pypi_0    pypi
pyreadline                2.1                      pypi_0    pypi
python                    3.9.20               h8205438_1    defaults
python-dateutil           2.9.0.post0              pypi_0    pypi
python-dotenv             1.0.1                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytracik                  0.0.1                    pypi_0    pypi
pytz                      2024.2                   pypi_0    pypi
pywin32                   308                      pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
pyzmq                     24.0.1           py39hea35a22_1    conda-forge
ray                       2.38.0                   pypi_0    pypi
referencing               0.35.1                   pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
retrying                  1.3.4                    pypi_0    pypi
rich                      13.9.4                   pypi_0    pypi
rpds-py                   0.20.1                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
rtree                     1.3.0                    pypi_0    pypi
ruamel-yaml               0.18.6                   pypi_0    pypi
ruamel-yaml-clib          0.2.12                   pypi_0    pypi
scikit-image              0.22.0                   pypi_0    pypi
scikit-learn              1.5.2                    pypi_0    pypi
scipy                     1.13.1                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                75.1.0           py39haa95532_0    defaults
shapely                   2.0.6                    pypi_0    pypi
shellingham               1.5.4                    pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
smart-open                7.0.5                    pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
sqlite                    3.45.3               h2bbff1b_0    defaults
stack-data                0.6.3                    pypi_0    pypi
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
starlette                 0.41.2                   pypi_0    pypi
sympy                     1.13.1                   pypi_0    pypi
tenacity                  9.0.0                    pypi_0    pypi
tensorboard               2.18.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tensorboardx              2.6.2.2                  pypi_0    pypi
thop                      0.1.1-2209072238          pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2024.8.30                pypi_0    pypi
torch                     2.2.2+cu121              pypi_0    pypi
torchaudio                2.2.2+cu121              pypi_0    pypi
torchvision               0.17.2+cu121             pypi_0    pypi
tornado                   6.2              py39ha55989b_1    conda-forge
tqdm                      4.66.6                   pypi_0    pypi
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
typer                     0.12.5                   pypi_0    pypi
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024.2                   pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_1    conda-forge
ultralytics               8.0.220                  pypi_0    pypi
urllib3                   2.2.3                    pypi_0    pypi
uvicorn                   0.32.0                   pypi_0    pypi
vc                        14.40                h2eaa2aa_1    defaults
virtualenv                20.27.1                  pypi_0    pypi
vs2015_runtime            14.40.33807          h98bb1dd_1    defaults
watchfiles                0.24.0                   pypi_0    pypi
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
websockets                13.1                     pypi_0    pypi
werkzeug                  3.0.6                    pypi_0    pypi
wheel                     0.44.0           py39haa95532_0    defaults
widgetsnbextension        4.0.13                   pypi_0    pypi
wrapt                     1.16.0                   pypi_0    pypi
yarl                      1.17.1                   pypi_0    pypi
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.20.2             pyhd8ed1ab_0    conda-forge



'''