# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rviz.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rviz.proto',
  package='Rviz',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nrviz.proto\x12\x04Rviz\"\x07\n\x05\x45mpty\"\x1b\n\x0b\x43odeRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x0c\"3\n\x15\x43reateInstanceRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"U\n\x06Status\x12\'\n\x05value\x18\x01 \x01(\x0e\x32\x18.Rviz.Status.StatusValue\"\"\n\x0bStatusValue\x12\t\n\x05\x45RROR\x10\x00\x12\x08\n\x04\x44ONE\x10\x01\x32u\n\x04RViz\x12-\n\x08run_code\x12\x11.Rviz.CodeRequest\x1a\x0c.Rviz.Status\"\x00\x12>\n\x0f\x63reate_instance\x12\x1b.Rviz.CreateInstanceRequest\x1a\x0c.Rviz.Status\"\x00\x62\x06proto3'
)



_STATUS_STATUSVALUE = _descriptor.EnumDescriptor(
  name='StatusValue',
  full_name='Rviz.Status.StatusValue',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DONE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=162,
  serialized_end=196,
)
_sym_db.RegisterEnumDescriptor(_STATUS_STATUSVALUE)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Rviz.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=27,
)


_CODEREQUEST = _descriptor.Descriptor(
  name='CodeRequest',
  full_name='Rviz.CodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='Rviz.CodeRequest.code', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=56,
)


_CREATEINSTANCEREQUEST = _descriptor.Descriptor(
  name='CreateInstanceRequest',
  full_name='Rviz.CreateInstanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Rviz.CreateInstanceRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='Rviz.CreateInstanceRequest.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=109,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='Rviz.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Rviz.Status.value', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATUS_STATUSVALUE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=196,
)

_STATUS.fields_by_name['value'].enum_type = _STATUS_STATUSVALUE
_STATUS_STATUSVALUE.containing_type = _STATUS
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['CodeRequest'] = _CODEREQUEST
DESCRIPTOR.message_types_by_name['CreateInstanceRequest'] = _CREATEINSTANCEREQUEST
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'rviz_pb2'
  # @@protoc_insertion_point(class_scope:Rviz.Empty)
  })
_sym_db.RegisterMessage(Empty)

CodeRequest = _reflection.GeneratedProtocolMessageType('CodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _CODEREQUEST,
  '__module__' : 'rviz_pb2'
  # @@protoc_insertion_point(class_scope:Rviz.CodeRequest)
  })
_sym_db.RegisterMessage(CodeRequest)

CreateInstanceRequest = _reflection.GeneratedProtocolMessageType('CreateInstanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEINSTANCEREQUEST,
  '__module__' : 'rviz_pb2'
  # @@protoc_insertion_point(class_scope:Rviz.CreateInstanceRequest)
  })
_sym_db.RegisterMessage(CreateInstanceRequest)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'rviz_pb2'
  # @@protoc_insertion_point(class_scope:Rviz.Status)
  })
_sym_db.RegisterMessage(Status)



_RVIZ = _descriptor.ServiceDescriptor(
  name='RViz',
  full_name='Rviz.RViz',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=198,
  serialized_end=315,
  methods=[
  _descriptor.MethodDescriptor(
    name='run_code',
    full_name='Rviz.RViz.run_code',
    index=0,
    containing_service=None,
    input_type=_CODEREQUEST,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='create_instance',
    full_name='Rviz.RViz.create_instance',
    index=1,
    containing_service=None,
    input_type=_CREATEINSTANCEREQUEST,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RVIZ)

DESCRIPTOR.services_by_name['RViz'] = _RVIZ

# @@protoc_insertion_point(module_scope)
